server:
  port: ${PORT:8081}
logging:
  level.org.atmosphere: warn

spring:
  mustache:
    check-template-location: false
  servlet:
    multipart.max-file-size: 50MB
    multipart.max-request-size: 50MB
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console
#
vaadin:
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,com.esp.espflow, com.flowingcode, com.infraleap
  # Launch the default browser when starting the application in development mode
  launch-browser: true
  frontend:
    hotdeploy: true
  copilot:
    enable: false

login:
  access-name: ${ADMIN_ESPFLOW_USER}
  access-password: ${ESPFLOW_PASSWORD}